### PR TITLE
Add iOS and macOS support

### LINKED ISSUE #1: iOS support
I'm just trying to write the duration to an audio file but the following error is thrown every time:

```
flutter: Invalid argument(s): Failed to lookup symbol 'store_dart_post_cobject': dlsym(RTLD_DEFAULT, store_dart_post_cobject): symbol not found
flutter: 
#0      DynamicLibrary.lookup (dart:ffi-patch/ffi_dynamic_library_patch.dart:34:70)
#1      RustWire._store_dart_post_cobjectPtr (package:metadata_god/src/bridge_generated.dart:540:62)
#2      RustWire._store_dart_post_cobjectPtr (package:metadata_god/src/bridge_generated.dart)
#3      RustWire._store_dart_post_cobject (package:metadata_god/src/bridge_generated.dart:543:7)
#4      RustWire._store_dart_post_cobject (package:metadata_god/src/bridge_generated.dart)
#5      RustWire.store_dart_post_cobject (package:metadata_god/src/bridge_generated.dart:534:12)
#6      StoreDartPostCObjectExt.storeDartPostCObject (package:flutter_rust_bridge/src/ffi/io.dart:15:5)
#7      FlutterRustBridgeBase._setUpRustToDartComm (package:flutter_rust_bridge/src/basic.dart:39:11)
#8      new FlutterRustBridgeBase (package:flutter_rust_bridge/src/basic.dart:22:5)
#9      new RustImpl.raw (package:metadata_god/src/bridge_generated.dart:77:34)
#10     new RustImpl (package:metadata_god/src/bridge_generated.d<…>
flutter: ----------------------------------------------------
```

Version: 0.2.0
Platform: IPhone Simulator
OS: iOS 16

EDIT: Sorry, didn't see, that iOS ist not supported. Is iOS support planned for the future?

### PR DESCRIPTION
**Pull request by mouEsam**
This PR adds support for macOS and iOS.

Closes #1

### CODE REVIEW

**Comment by KRTirtho** [comment]
Does the example app runs perfectly fine one macOS? (with actual audio file path) :smiley:

**Comment by KRTirtho** [comment]
Hey looks like macos version is not working and the example app throwing following error
image

**Comment by KRTirtho** [comment]
Looks like `macos/Frameworks/rust_crate.framework/Versions/A/rust_crate` is a static reference so it won't work anywhere except your own macOS instance :sweat_smile: . Can't we directly put the `librust.dylib` in `macos/Frameworks/rust_crate.framework/Versions/A` renaming to `rust_crate`?

**Comment by shadow5688** [comment]
@mouEsam can https://github.com/KRTirtho/metadata_god/issues/26 be looked into please?

**Comment by mouEsam** [comment]
> @mouEsam can https://github.com/KRTirtho/metadata_god/issues/26 be looked into please?

Gladly tomorrow 👍

**Comment by shadow5688** [comment]
> Gladly tomorrow 👍

Hey @mouEsam, Were you able to look into it? If there's something needed from my end, then lemme know

**Pull request merged**
