### PR TITLE
Use lofty-rs for metadata instead of audiotags

### LINKED ISSUE #15: Use lofty-rs for reading metadata instead of audiotags
Lofty-rs has support for many more filetypes than audiotags. That way metadata-god can also support reading ogg,opus and wav metadata. 
https://github.com/Serial-ATA/lofty-rs

### PR DESCRIPTION
**Pull request by FriederHannenheim**
This is a bit of a quick and dirty implementation. The api could be changed so that not so many type conversions would be needed. I'm not really sure how the bindings work though so I didn't change it now.
This fixes #15 and enables reading many more types of tags.
Downside: album_artist isn't supported by lofty and is just mapped to artist

### CODE REVIEW

**Comment by FriederHannenheim** [comment]
Wait. Don't merge this yet. Lofty does support album artist. I just didn't see it since there is no direct method for it.

**Comment by FriederHannenheim** [comment]
Alright. Album Artist is now working correctly

**Comment by KRTirtho** [comment]
Wow that's a wonderful and huge work :heart: :rocket:

**Comment by KRTirtho** [comment]
@FriederHannenheim sorry for the delay. I've checked it and your implementation works quite well

**Comment by KRTirtho** [comment]
But what will do about the `CMakeLists.txt` and `pubspec.yaml` changes?
After merging this I'm planning to publish it as `v0.5.0`

Since you're actively using the fork's `main` branch aka this branch in an app I suggest you to close this PR and create a new one with `pubspec` and `CMakeLists.txt` changes reverted using a separate branch

**Comment by FriederHannenheim** [comment]
Alright new, cleaner pull request is #21

**Pull request closed without merging**
