### PR TITLE
Use lofty-rs for metadata instead of audiotags

### LINKED ISSUE #15: Use lofty-rs for reading metadata instead of audiotags
Lofty-rs has support for many more filetypes than audiotags. That way metadata-god can also support reading ogg,opus and wav metadata. 
https://github.com/Serial-ATA/lofty-rs

### PR DESCRIPTION
**Pull request by FriederHannenheim**
Replaces #17. Fixes #15

### CODE REVIEW

**Comment by FriederHannenheim** [comment]
For now this uses my own lofty-rs fork, which is a bit more relaxed when parsing tags. Upstream lofty will just error if the tag is invalid. My patch allows it to return the valid tags. 
A feature for lofty is planned to implement a Relaxed ReadingMode which would do the same thing. Then upstream lofty can be used. https://github.com/Serial-ATA/lofty-rs/issues/204#issuecomment-1573942708

**Comment by KRTirtho** [comment]
LGTM and works fine too

**Comment by KRTirtho** [comment]
metadata_god v0.5.0 is published to pub.dev
@FriederHannenheim Thanks a lot for this amazing contribution. You basically re-wrote entire lib :smile: :rocket:

**Comment by Feichtmeier** [comment]
@FriederHannenheim are bits missing to make metadata god read out ogg files?

**Pull request merged**
